version: '3.7'
services:
  db:
    container_name: postgres_todo
    image: postgres:latest
    environment:
      POSTGRES_USER: sqluser
      POSTGRES_PASSWORD: sqlpass
      POSTGRES_DB: psql_db
    volumes:
      - postgresdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgresdata: